Reg Add "HKLM\SYSTEM\CurrentControlSet\Services\Psched" /v "Start" /t Reg_DWORD /d "1" /f > $null 2>&1
Start-Service -Name "Psched" > $null 2>&1
Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS" /f > $null 2>&1
$processes = @(
"csgo", 
"VALORANT-Win64-Shipping", 
"League of Legends", 
"witcher3", 
"RDR2", 
"RocketLeague", 
"bfv",
"StarWarsJediFallenOrder", 
"ACValhalla", 
"FIFA21", 
"Sekiro", 
"DarkSoulsIII", 
"MonsterHunterWorld", 
"TESV", 
"Fallout4", 
"Hades", 
"Terraria", 
"Stardew Valley", 
"Three_Kingdoms", 
"SC2", "worldoftanks", 
"PathOfExile_x64", 
"TS4_x64", 
"re3", 
"re7", 
"CivilizationVI_DX12", 
"CivilizationVI", 
"DeadByDaylight-Win64-Shipping", 
"ffxiv_dx11", 
"ffxiv", 
"GhostOfTsushima", 
"Warframe.x64", 
"TheDivision2", 
"FarCry5", 
"Hearthstone", 
"HeroesOfTheStorm_x64", 
"MassEffectLauncher", 
"deadspace", 
"Wow", 
"Wow-64", 
"RainbowSix", 
"TslGame", 
"GTA5", 
"javaw", 
"FortniteClient-Win64-Shipping", 
"ModernWarfare", 
"r5apex", 
"ultrakill", 
"RobloxPlayerBeta", 
"Call of Duty Launcher", 
"cod", 
"DeadByDaylight-EGS-Shipping", 
"launcher", 
"GenshinImpact", 
"Cyberpunk2077", 
"Overwatch", 
"osu!", 
"hl2", 
"destiny2", 
"hammer", 
"dota2", 
"ShippingPC-BattleGame", 
"Smite", 
"r5apex_d12", 
"csgo_legacy_app", 
"cs2", 
"Among Us", 
"Minecraft.Windows", 
"HaloInfinite", 
"GeometryDash", 
"t6mp",
"needforspeedunbound"
"spv3",
"forzahorizon5",
"jedisurvivor",
"SkyrimVR",
"SkyrimSE",
"Vail",
"BioShockInfinite", 
"deadcells", 
"IndianaEpicGameStore-Win64-Shipping", 
"Control_DX12", 
"ForzaHorizon4", 
"NieRAutomata", 
"HITMAN2", 
"Hollow_Knight", 
"Risk of Rain 2", 
"Anno1800", 
"MK11", 
"mgsvtpp", 
"Dishonored2", 
"Subnautica", 
"SubnauticaZero", 
"Diablo III64", 
"ffxv_s", 
"MetroExodus", 
"aces", 
"EliteDangerous64", 
"factorio", 
"bg3", 
"ck3", 
"eu4", 
"isaac-ng", 
"OxygenNotIncluded", 
"Phasmophobia", 
"RimWorldWin64", 
"Bloodborne",
"Battlefield2042", 
"GuildWars2-64", 
"StarCitizen", 
"Paladins", 
"Brawlhalla", 
"StreetFighterV", 
"Tekken7", 
"ElderScrollsOnline", 
"BlackDesertOnline", 
"EscapeFromTarkov", 
"DayZ", 
"RustClient", 
"RealmRoyale", 
"StarWarsBattlefrontII", 
"F12021", 
"NBA2K21", 
"WarhammerVermintide2", 
"NoMansSky", 
"FFXIVLauncher", 
"PlanetSide2_x64", 
"ARKSurvivalEvolved", 
"AgeOfEmpiresIV", 
"ForHonor", 
"Titanfall2", 
"Splatoon2", 
"Overcooked2", 
"RocketArena",
"witcher2",
"FallGuys_client",
"hoi4"
"Cemu",
"rpcs3",
"payday2_win32_release",
"dontstarve_steam",
"TheForest",
"ConanSandbox",
"Warhammer",
"stellaris",
"eso64",
"MCC-Win64-Shipping",
"Dolphin",
"pcsx2",
"ppssppwin32",
"ePSXe",
"yuzu",
"Ryujinx",
"zsnesw",
"snes9x",
"citra-qt",
"higan",
"EmuHawk",
"RetroArch",
"Project64",
"HD-Player",
"mGBA",
"VRChat",
"Secret Neighbour",
"SCPSL",
"Crab Game",
"RainbowSix_Vulkan",
"BlackOps3",
"BlackOpsColdWar"
)
foreach ($i in $processes) {
    if (!(Test-Path "HKLM:\Software\Policies\Microsoft\Windows\QoS\$i")) {
		Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /f > $null 2>&1
    }
	Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /v "Application Name" /t Reg_SZ /d "$i.exe" /f > $null 2>&1
	Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /v "Version" /t Reg_SZ /d "1.0" /f > $null 2>&1
	Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /v "Protocol" /t Reg_SZ /d "*" /f > $null 2>&1
	Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /v "Local Port" /t Reg_SZ /d "*" /f > $null 2>&1
	Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /v "Local IP" /t Reg_SZ /d "*" /f > $null 2>&1
	Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /v "Local IP Prefix Length" /t Reg_SZ /d "*" /f > $null 2>&1
	Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /v "Remote Port" /t Reg_SZ /d "*" /f > $null 2>&1
	Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /v "Remote IP" /t Reg_SZ /d "*" /f > $null 2>&1
	Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /v "Remote IP Prefix Length" /t Reg_SZ /d "*" /f > $null 2>&1
	Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /v "DSCP Value" /t Reg_SZ /d "46" /f > $null 2>&1
	Reg Add "HKLM\Software\Policies\Microsoft\Windows\QoS\$i" /v "Throttle Rate" /t Reg_SZ /d "-1" /f > $null 2>&1
}
Reg Add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Psched\DiffservByteMappingConforming" /v "ServiceTypeGuaranteed" /t REG_DWORD /d "46" /f > $null 2>&1
Reg Add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Psched\DiffservByteMappingConforming" /v "ServiceTypeNetworkControl" /t REG_DWORD /d "56" /f > $null 2>&1
Reg Add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Psched\DiffservByteMappingNonConforming" /v "ServiceTypeGuaranteed" /t REG_DWORD /d "46" /f > $null 2>&1
Reg Add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Psched\DiffservByteMappingNonConforming" /v "ServiceTypeNetworkControl" /t REG_DWORD /d "56" /f > $null 2>&1
Reg Add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Psched\UserPriorityMapping" /v "ServiceTypeGuaranteed" /t REG_DWORD /d "5" /f > $null 2>&1
Reg Add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Psched\UserPriorityMapping" /v "ServiceTypeNetworkControl" /t REG_DWORD /d "7" /f > $null 2>&1
Reg Add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Psched" /v "MaxOutstandingSends" /t REG_DWORD /d "65000" /f > $null 2>&1
